--Task table
CREATE TABLE task (
      id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      short_desc varchar(255) not null,
      details text,
      start_date date not null,
      end_date date,
      group_id   BIGINT REFERENCES "group" (id)
);

create sequence task_sequence start with 1 increment by 1;

INSERT INTO task (short_desc, details, start_date, end_date, group_id)
VALUES ('Task 1', 'This is task 1', '2024-03-18', '2024-03-24', 1);

